[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://finflow-production-e4b3.up.railway.app"
  REACT_APP_VERSION = "2.1.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 