[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://finflow-production-e4b3.up.railway.app"
  REACT_APP_VERSION = "2.1.0"
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Configuração para React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações adicionais para melhor performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Configurações de cache para melhor performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 